name: Test - Container Image Build

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pratikimprowise/nginx_proxy:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test with curl
        run: |
          set +e
          docker images -a --filter "reference=nginx_proxy"
          docker run -d --name nginx_proxy nginx_proxy:latest
          sleep 5
          nginx_proxy_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx_proxy)
          err=1
          count=0
          while [[ $err != 0 ]]; do
            curl -sSLv -x $nginx_proxy_ip:8888 --max-time 10 ifconfig.io
            err=$?
            [[ $err == 0 ]] && exit 0
            count=$(( count + 1 ))
            [[ $count -ge 5 ]] && exit 1
          done

      - name: Stop containers and show logs
        if: always()
        run: |
          docker exec -i nginx_proxy cat /var/log/nginx_errors.log || true
          docker exec -i nginx_proxy cat /var/log/nginx_access.log || true
          docker rm -f nginx_proxy || true
