name: Test - Container Image Build

on:
  push:
    branches: [master,develop]
  pull_request:
    branches: [master,develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the Docker image
        run: |
          ((docker images -a | grep -vE ubuntu.\*20.04 | awk '{print $3}' | xargs docker rmi -f) || true) &
          wait_rm=$!
          docker-compose -f docker-compose.yaml up -d --build
          docker images -a
          wait $wait_rm

      - name: Test with curl
        run: |
          nginx_proxy_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx_proxy)
          err=1
          count=0
          while [[ $err != 0 ]]; do
            curl https://www.google.com -svo /dev/null -x $nginx_proxy_ip:8888
            err=$?
            [[ $err == 0 ]] && exit 0
            count=$(( count + 1 ))
            [[ $count -ge 5 ]] && exit 1
          done

      - name: Stop containers and show logs
        if: always()
        run: |
          docker exec -i nginx_proxy cat /var/log/nginx_errors.log || true
          docker exec -i nginx_proxy cat /var/log/nginx_access.log || true
          docker-compose -f docker-compose.yaml down || true
